language: go
go: 
  - 1.11.x
before_install:
  - nvm install 10.7.0
  - export GO111MODULE=on
install:
  - go mod download
  - cd app/ && npm install && cd ../
script:
  - make
  
notifications:
  email: false

  