language: go
go: 
  - 1.11.x
before_install:
  - nvm install 10.7.0
  - export GO111MODULE=on
install:
  - go mod download
  - cd app/ && npm install && cd ../
script:
  - make

deploy:
  provider: codedeploy
  access_key_id: AKIAILZZNNW2UR7S46QQ
  secret_access_key:
    secure: "gBg4nPtKnHViGvoODsCzPmadhnQ3XqItxKxXLOVlGJTARkh1t5xh+7VNvt1ahlhq7ZRT6DJY0qi9eaq1DbBGW4wppgu/JZjD6vcJfEv8Jr75EXn3X0YGrtQbRZWJPy8WetujqTaueKBlyZ9vgqtkT0K1KWxs7G9Uaf0BJR9mK2bZfApZGWz0qeQu2bU0llGkOXnphlNaQU0cTfNqaoUQ7ngL3Ju8aJrScU8DeBQpdSurYMn9PXDynvkcNLulp77ixTOuUDa3beUTlPz4PQq3v35g8jbTbNS/gbWq1YnohgxfhCcOyXPRsqCKUpgPc2UVpJl3UEpXlEyq9oVYnj20ZNiKSujdTJ/+0WLXEI+X3IdJHvdfRAs0pRuKFyrGkWKQk0OtizieNj0FP3PWKwGTQM+uN+1zyNqcDDQxw2+kW6WW86sNirjv3aqYjBuAaSlxRfp4rhcCqJhkP3TsnXxn/hjhyA1+TYp8K/gxJqTpdCMUCxiaYlwmyEMlFN00VC5bWeLnD+YsV4Q/rj3O/QvTl/j82X83FK5Hgp5g9QKyyE8yANlL/a5YqbgIDMeXi817iIKPMVfBEK+j42ukUWqLH1xpOnxZ/Q1GR5BPP++0OVHBCRa1dJduQPQaaDnr6Yu7fLx+PMauPtIQUvUbJNA/UqHaNMmVZ6m1kvn2OP6pqqw="
  bucket: "cherie.website"
  key: app.tar.gz
  bundle_type: .tar.gz
  application: trello-transform
  deployment_group: Normal-Deploy
  
notifications:
  email: false

  